# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  gripper_l_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_l_joint_m:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_r_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_r_joint_m:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robl_joint_1:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robl_joint_2:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robl_joint_3:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robl_joint_4:
    has_velocity_limits: true
    max_velocity: 6.98131700798
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robl_joint_5:
    has_velocity_limits: true
    max_velocity: 6.98131700798
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robl_joint_6:
    has_velocity_limits: true
    max_velocity: 6.98131700798
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robl_joint_7:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robr_joint_1:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robr_joint_2:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robr_joint_3:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robr_joint_4:
    has_velocity_limits: true
    max_velocity: 6.98131700798
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robr_joint_5:
    has_velocity_limits: true
    max_velocity: 6.98131700798
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robr_joint_6:
    has_velocity_limits: true
    max_velocity: 6.98131700798
    has_acceleration_limits: false
    max_acceleration: 0
  yumi_robr_joint_7:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: false
    max_acceleration: 0